#Deployment Rolling Update manifest file creating pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-pod 
  namespace: test-ns
spec:
  replicas: 2
  selector:
     matchlabels:
       app: nginx-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge: 1
       maxUnavailable: 1
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx-image
        image: nginx
        ports:
        - containerPort: 8080
          name: nginxport
---
#service creating for RollingUpdate Deployment
apiVersion: v1
kind: Deployment
metadata:
   name: nginx-svc
   namespace: test-ns
spec:
  type: NodePort
  selector: 
    app: nginx-app
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 32100
    protocal: TCP

      