#Deployment Recreate pod crating 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector: 
    matchLabels:
       app: nginx-pod
  template:
    metadata:
      lables:
        app: nginx-pod
    spec:
      containers:
      - name: nginx-image
        image: nginx
        ports:
        - containerPort: 80
---
# service cerate for this deployment
apiVersion: v1
kind: Service 
metadata:
  name: nginx-svc
spec:
  type: NodePort
  selector: 
    app: nginx-pod
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 32001

    