#RC(ReplicationController)Pod creaded 
apiVersion: v1
kind: ReplicationController
metadata: 
  name: nginx-RC-pod
spec:
  replicas: 2
  selector:
    app: nginx
  template:
    metadata:
      name: nginx
      lables:
        app: nginx
    spec:
      containers:
      - name: nginximage
        image: nginx
        ports:
        - containerPort: 8080
---
#service created for port export to internet
apiVersion: v1
kind: Service
metadata: 
  name: nginx-rcsvc
spec: 
  type: NodePort
  selector: 
    app: nginx
  ports:
  - port: 80
    targetPort: 8080
    protocal: TCP

