#RS(ReplicaSet)Pod creating by RS
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: nginx-RS-pod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-pod
  template:
    metadata:
      labels:
        app: nginx-pod
    spec:
      containers:
      - name: nginximage
        image: nginx
        ports:
        - containerPort: 8080
---
#service created for RS pod 
apiVersion: v1
kind: Service
metadata: 
  name: nginx-rs-svc
spec:
  type: NodePort
  selector: 
    app: nginx-pod
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30031
    protocal: TCP



